# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:            pretty
relative_permalinks:  false

# Setup
title:                'Ownbin'
tagline:              'Life is a gift'
#description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:          'Just some records, have fun!'
url:                  ''  # the base hostname & protocol for your site
baseurl:              ''  # the subpath of your site, e.g. /blog/
logourl:              /assets/images/logo.png # Site logo
paginate:             5

# About/contact
author:
  name:               Ownbin Ho
  url:                https://twitter.com/ownbin     
  contact:
    linkedin:         https://www.linkedin.com/
    github:           https://github.com/ownbin
    # facebook:  <hide>
    twitter:          https://twitter.com/ownbin
    weibo:            http://weibo.com/ownbin
    email:            mailto:ownbin@hotmail.com

# Custom vars
version:              1.0.0

sass:
  sass_dir:           _sass
  style:              compressed

tag_page:             '/tags/'
repo_name:            'ownbin/ownbin.github.io' # for getting the comments on github issues
#repo_name:            'dwilliamson/donw.io'
